export const DEFAULT_TIER_REVENUES = [500, 1200, 3000, 7500];
export const DEFAULT_MARKETING_BUDGET = 10000;
export const DEFAULT_COST_PER_LEAD = 150;
export const DEFAULT_CONVERSION_RATE = 2.5; // percent
export const DEFAULT_MONTHLY_CHURN_RATE = 3; // percent
export const DEFAULT_WACC = 8; // percent
export const DEFAULT_INITIAL_CAC_SMB = 239;
export const DEFAULT_PROJECTION_MONTHS = 24;
export const DEFAULT_INITIAL_INVESTMENT = 200000;
export const DEFAULT_OPERATING_EXPENSE_RATE = 35;
export const DEFAULT_FIXED_COSTS = Math.round(50000 / 12);
